### ISSUE TITLE
Bug in ListColumn 

### ISSUE THREAD

**Issue by hant121** [hantbk/taskflow#44]
Khi tạo quá nhiều card trong giao diện thì sẽ ẩn nút add card. Nút Add Card không hiện cho người dùng

**Comment by hantbk** [comment]
To ensure that the "Add a card" button and footer are always visible within the viewport, you can apply position: 'sticky' to the Box wrapping the footer. This will keep it "stuck" to the bottom of the column, even when there are many cards in the column
